### ISSUE TITLE
Can't craft certain recipes; can't find pattern for why not

### ISSUE THREAD

**Issue by Not-February** [ochotonida/presents#1]
https://hastebin.com/refamumolo.md

I have had a LOT of trouble trying to figure out what is causing this particular issue - some recipes inexplicably cause this error when they are placed in the crafting grid, and I could not find a common factor in my modpack. The recipes affected are always the same, and it doesn't seem to matter what size, shape, or mod the recipe is from. I've narrowed down one culprit in a commonly-used mod for a smaller-sized test, though.

I made a smaller test instance with nothing but JEI, Presents, and Quark/AutoRegLib(since one of the recipes I know that isn't working is from Quark). I cannot craft the "Paper Lamp" from Quark despite using the correct recipe for it, and worse yet: after I try to craft that paper lamp even ONCE in-game, the recipe won't even show up in JEI again as a valid recipe until I restart the game entirely.

Removing Presents causes the issue to cease entirely.

I am assuming this is either an issue with JEI or Presents, since Quark is not the only mod affected(I also had some custom recipes from Crafttweaker affected, but couldn't find a common factor). In a larger modpack with custom recipes, you can probably guess which has the higher priority of staying.

I'd love to have this mod of yours during the holiday season, but not at the cost of basic functionality.

Mod versions used in this test:

Forge: 14.23.5.2768

Just Enough Items: 1.12.2-4.13.1.225
Presents: 1.12.2-1.1.0
AutoRegLib: 1.3-21
Quark: r1.5-134

**Comment by ochotonida** [comment]
I've fixed the issue, I'm terribly sorry it took me so long. A patch should be available soon

**Comment by Not-February** [comment]
Super glad to hear! I'll happily throw this back into my pack soonish. :)
