### ISSUE TITLE
Crashes on server with java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IBlockColor

### ISSUE THREAD

**Issue by Niko-sk2x** [ochotonida/presents#2]
I didn't try this mod myself, but I've seen someone run into this issue on discord, and verified that there is in fact an issue in the code:
https://github.com/ochotonida/presents/blob/2af713fe7b263904ee3e8d4b9421dbefd9f312ac/src/main/java/presents/Presents.java#L64-L67

**Comment by Sunconure11** [comment]
https://pastebin.com/yph3bNyR

That was probably me who posted about the error.

**Comment by Sunconure11** [comment]
@ochotonida

**Comment by ochotonida** [comment]
I'm sorry I didn't see this sooner, I have been quite busy the past few days and for some reason didn't get notified. I've fixed the issue and will bring out a patch very soon
